
[tools]
# yazi dependencies
"ubi:sharkdp/fd" = "10.3.0"
"ubi:junegunn/fzf" = "0.67.0"
"ubi:BurntSushi/ripgrep" = { version = "15.1.0", exe = "rg" }

# development tools
"ubi:JohnnyMorganz/stylua" = "2.3.1"
actionlint = "1.7.10"
